#!/bin/sh

kubectl create -f local-storageclass.yml 
kubectl create -f redis-deployment.yml
kubectl create -f redis-service-clusterip.yml
kubectl create -f myapp-configMap.yml
kubectl create -f myapp-secret.yml
kubectl create -f persistent-volume-definition.yml
kubectl create -f postgres-pvc.yml
kubectl create -f postgres-deployment.yml
kubectl create -f postgres-service-clusterip.yml
kubectl create -f postgres-configMap.yml
kubectl create -f ingress-service.yml
kubectl create -f mybackend-deployment.yml
kubectl create -f mybackend-service-clusterip.yml
kubectl create -f myfrontend-deployment.yml
kubectl create -f myfrontend-service-clusterip.yml
