#!/bin/sh

kubectl delete service mypostgresservice
kubectl delete service myredisservice
kubectl delete service myapp-backend-clusterip
kubectl delete service myapp-frontend-clusterip
kubectl delete deployments,pods,configMaps,ingresses --all
kubectl delete pvc postgres-pvc
kubectl delete pv pv-volume1
kubectl delete sc local-storage
kubectl delete secret myapp-secret
