
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:3000"
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    tty: true
