apiVersion: apps/v1

kind: Deployment

metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: frontend

spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: frontend
        
        spec:
            containers:
                - name: frontend-app
                  image: realityarchitect/myfrontend

    replicas: 3
    selector: 
        matchLabels:
            type: frontend
